### ISSUE TITLE
Focus on clinically relevant fusions

### ISSUE THREAD

**Issue by obigriffith** [griffithlab/civic-meeting#1]
Currently, clinically relevant fusions are under-represented in CIViC (and other knowledgebases) in relation to SNVs and other small mutations. Fusions represent a unique curation challenge in CIViC as they involve multiple genes and multiple (sometimes difficult to define) genomic coordinate sets. They also represent unique challenges for developing NGS sequencing panels and may require specific technologies (e.g., Archer) to identify them. However, many fusions have clear implications for prognosis, diagnosis, or drug response. I propose a working group to tackle the specific challenge of curating fusions in CIViC.

**Comment by malachig** [comment]
+1. In comparison to SNV and Indels, variants of this type have much less information from supporting resources.  For example, there are many resources that allow one to assess the level of recurrence for a particular SNV. One topic of discussion for this working group could be to identify what resources, tools, and best practices relevant to fusions already do exist, and what the major knowledge/resource gaps are.
