### ISSUE TITLE
Motivating Participation for Scientific Curation of Somatic Variants for Clinical Actionability

### ISSUE THREAD

**Issue by GenomeDeb** [griffithlab/civic-meeting#19]
Interested to discuss how to motivate people to participate in curation efforts. Wall of shame (or tracking participation), rewards associated with achieving levels, points, reminders of contributions, small completable tasks, goal setting/goal completions, any thoughts to tie this into health apps like vitality etc -- i.e. companies pay for healthy workers, maybe interested to pay for healthy science participation too?

**Comment by ahwagner** [comment]
We've implemented badges, and they seem to motivate some of our users. We have also implemented user and organization leaderboards.

However, there's so much more we should be doing here. It's a great, ongoing question.
