### ISSUE TITLE
save Add Evidence form state on exit from page, restore state upon return

### ISSUE THREAD

**Issue by jmcmichael** [griffithlab/civic-meeting#21]
Would be nice to have a feature where complex form's state (such as Add Evidence) were saved when a user exits a page, to be restored when they return.

**Comment by ahwagner** [comment]
Issue moved to [griffithlab/civic-client #922](https://github.com/griffithlab/civic-client/issues/922) via [**ZenHub**](https://www.zenhub.com/)
