### ISSUE TITLE
SOP and evidence codes for somatic variant oncogenicity/clinical actionability

### ISSUE THREAD

**Issue by arpaddanos** [griffithlab/civic-meeting#28]

**Comment by ahwagner** [comment]
Marilyn Li notes that common practice is to use somatic evidence in the interpretation of a germline variant, and vice-versa.

**Comment by ahwagner** [comment]
The group discussed the need for citing use of specific resources in a standard. Agreed that there is a need for a specific workflow in standards, but that evolving practice changes what those workflows look like. Thus, we need to arrive at a solution that provides both specificity and flexibility for evolving practices.

**Comment by malachig** [comment]
Proposal to use two genes, TP53 and PTEN as a proof-of-principle experiment for a combined germline and somatic variant interpretation guideline scheme that is based on the ACMG germline guidelines but incorporates fundamental somatic evidence concepts.

**Comment by arpaddanos** [comment]
[PostV1.pdf](https://github.com/griffithlab/civic-meeting/files/2488835/PostV1.pdf)

**Comment by arpaddanos** [comment]
ASHG poster PostV1.pdf summarizes the main ideas from this session as well as a model for how CIViC can adapt oncogenicity codes utilizing the proposed new Biological Evidence Item as well as Biological Assertion based on Oncogenicity Codes.
