### ISSUE TITLE
Integrate CIViC with genome browsers (igv.js, JBrowse, ...)

### ISSUE THREAD

**Issue by jrobinso** [griffithlab/civic-meeting#33]
Integrate the CIViC DB with genome browsers including igv.js,  JBrowse, and possibly IGV.   This integration could take 2 forms, not mutually exclusive

(1) Link out to CIViC from VCF and other variant track types  (e.g. SnpDB) and provide variant details in a popup.

(2)  When zoomed in to “gene” level, query the CIViC API for variants as genes come into view and display as a track.  Clicking on a variant would query the API and bring up details in a popup.

The motivation is to give researchers browsing their own variants in the genome browser easy access to CIViC data.   igv.js does a similar thing now with Cravat.    

If there is interest in this proposal I could outline an implementation approach here, or save it for the hackathon.

**Comment by ahwagner** [comment]
For progress on VCF exports, see in-progress issue: https://github.com/griffithlab/civicpy/issues/3

**Comment by jrobinso** [comment]
Thanks @ahwagner .    BTW,   I can't seem to apply a label (hackathon).  Perhaps I don't have the right premissions?

**Comment by ahwagner** [comment]
No, it looks as though labels are one of those things that requires a team member to set (https://help.github.com/articles/repository-permission-levels-for-an-organization/). Thanks for the heads-up, adding the hackathon label now.

**Comment by jrobinso** [comment]
Powerpoint  https://www.dropbox.com/s/kjl6l3a3i9yqw5t/Hackathon.pptx?dl=0
PDF  https://www.dropbox.com/s/hzpqejij6kpuqhq/Hackathon.pdf?dl=0
