### ISSUE TITLE
Improve CIViC WikiData integration

### ISSUE THREAD

**Issue by malachig** [griffithlab/civic-meeting#35]
Elevator pitch to be lead by Greg Stupp (Su lab) @stuppie

**Comment by stuppie** [comment]
I was thinking this could be a task to incorporate structured information about drugs into civic. Right now, we've mapped all of the drug names returned by the civic API to wikidata QIDs. It would be better if civic returned pubchem IDs which we could retrieve QIDs for.

https://github.com/SuLab/scheduled-bots/blob/master/scheduled_bots/civic/drugs.tsv

**Comment by stuppie** [comment]
Another idea is to take advantage of the sitelinks and label translations in Wikidata to "internationalize" civic. i.e. make available translations of diseases, drugs, or gene names.

**Comment by stuppie** [comment]
Pitch deck: https://docs.google.com/presentation/d/1NCmLT7unu6vdhPEBrdYyo30qy10l9EB6gurL8LgiUug/edit?usp=sharing

**Comment by acoffman** [comment]
[wikidata_mapping.tsv.zip](https://github.com/griffithlab/civic-meeting/files/2479932/wikidata_mapping.tsv.zip)

@stuppie, here's the list that @kkrysiak assembled

**Comment by NuriaQueralt** [comment]
NCIT - therapies:  http://bioportal.bioontology.org/ontologies/NCIT?p=classes&conceptid=http%3A%2F%2Fncicb.nci.nih.gov%2Fxml%2Fowl%2FEVS%2FThesaurus.owl%23C20401

**Comment by stuppie** [comment]
New updated list current as of oct 15 2018, with pmids
https://github.com/SuLab/scheduled-bots/blob/master/scheduled_bots/civic/drugname_pmid_oct_2018.csv

**Comment by mmayers12** [comment]
I've combined the two spreadsheets here:
https://docs.google.com/spreadsheets/d/1FL_Mim29q5Osloazj7rbNFoD4sdga247GE__qN1b4yc/edit?usp=sharing

**Comment by stuppie** [comment]
Some interesting drug issues:
https://docs.google.com/presentation/d/1C483_2h2cz6A2O4LFvlgGjVXXf1elpNnGW8KQCXuUXM/edit?usp=sharing
