### ISSUE TITLE
Modeling Variant Interpretations in SEPIO

### ISSUE THREAD

**Issue by malachig** [griffithlab/civic-meeting#36]
Elevator pitch to be lead by Matt Brush? @mbrush would you be able to give a ~3 minute elevator pitch on this and if there is interest help to lead a session on use of SEPIO?

**Comment by mbrush** [comment]
Sure, I'd be happy to!

**Comment by mbrush** [comment]
Link to pitch slides: https://www.dropbox.com/s/4s5gljkkh98s3ij/SEPIO_Pitch_20181015.pdf?dl=0
