### ISSUE TITLE
Best practices in annotating CNVs and fusions alongside variants in knowledgebases

### ISSUE THREAD

**Issue by bpitel12** [griffithlab/civic-meeting#39]
One noted gap in many well-known knowledgebases is the coverage and searchability of copy number variants and fusions/structural variants.  Many our our in-house tools are attempting to employ segment/coordinate based searches to link to relevant data/knowledge for clinical reporting of copy number variants.  Fusions are another beast for us - each assay seems to annotate things a little differently.  For example, are the fusion partners always listed 5' --> 3'?  How do we document structural rearrangements (translocations/inversions/CNVs) that result in over/under expression by position effect (i.e. they don't result in a fusion product)?

**Comment by anna-tanska** [comment]
That's a great topic. CNVs curation hasn't been well defined so far. Reporting and clinical actionability of CN poses many questions in our lab especially the ones that don't create a functional fusion but may still affect gene expression.

**Comment by bpitel12** [comment]
[CNV-SV.pptx](https://github.com/griffithlab/civic-meeting/files/2484513/CNV-SV.pptx)
