### ISSUE TITLE
Discussion of curation standards

### ISSUE THREAD

**Issue by obigriffith** [griffithlab/civic-meeting#4]
A group could be formed to discuss curation best practices, data model improvements, adoption of ClinGen (MVLD) and FDA proposals, ontologies, etc.

**Comment by malachig** [comment]
We should also keep our eyes out for the Association for Molecular Pathology (AMP) somatic guidelines that are apparently going to be published soon.

Other relevant works:

- [Standards and Guidelines for the Interpretation of Sequence Variants: A Joint Consensus Recommendation of the American College of Medical Genetics and Genomics and the Association for Molecular Pathology](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4544753/). 
- [An openly available online tool for implementing the ACMG/AMP standards and guidelines for the interpretation of sequence variants](http://www.nature.com/gim/journal/vaop/ncurrent/full/gim201613a.html)
