### ISSUE TITLE
Strategies for Variant Normalization & Representation

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/civic-meeting#41]

**Comment by ahwagner** [comment]
Slide deck: https://docs.google.com/presentation/d/1FlFZnEVoc0qBAyFMsQoZouXKGvrQtZqQkwspqlVcBQ4/edit?usp=sharing

**Comment by malachig** [comment]
Selected for discussion in the afternoon session.  12 participants attended.  Presentation lead by @ahwagner.
