### ISSUE TITLE
Curation: Building a Fact-checking companion dataset for CIViC (Room 309)

### ISSUE THREAD

**Issue by creisle** [griffithlab/civic-meeting#47]
I am planning to attend the upcoming meeting/jamboree and would like to propose backfilling/entering [CIViC NLI](https://creisle.github.io/civic-nli-ext) selections if there is still room for proposals. This would involve curators selecting evidence sentences/spans in PMC/pumbed articles which are support for existing (or new if preferred) CIViC evidence items.

Secondary Task: Labelling pre-compiled examples in doccano: https://bcgsc-doccano.herokuapp.com/

**Comment by malachig** [comment]
Resolving in preparation for the 2023 hackathon/jamboree.
