### ISSUE TITLE
Improve WHO book representation in ontologies (Room 307)

### ISSUE THREAD

**Issue by baileyglen** [griffithlab/civic-meeting#49]
- Work with NCI-Thesaurus to create entire WHO representations, similar to AML (https://nciterms.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&version=22.02d&code=C159157&ns=ncit)

- Establish list of relationships between who entities and the ICD codes

**Comment by kkrysiak** [comment]
CIViC accesses NCIt content by using their OBO file: https://stars.renci.org/var/NCIt/ncit.obo
Code to parse that file can be found here: https://github.com/griffithlab/civic-v2/blob/main/server/app/lib/importer/nci_thesaurus_mirror.rb

**Comment by malachig** [comment]
Bailey presented a summary on this team's discussions.

**Comment by malachig** [comment]
Resolving in preparation for the 2023 hackathon/jamboree.
