### ISSUE TITLE
Biophysical modeling for interpreting functional impacts

### ISSUE THREAD

**Issue by mccoymd** [griffithlab/civic-meeting#51]
Given the scale of potential variation, to what extent can protein-specific models of functional impact be used as evidence? 

I've been developing a method to predict functional changes of missense mutations using simulations of protein structure.

https://www.cell.com/biophysj/fulltext/S0006-3495(20)33203-3

In short, molecular dynamics (MD) simulations are used to define the characteristic "wobble" using an all atom representation of a variant's protein structure.  By projecting this variant specific profiles into a lower dimensional space (PCA), we find that variants cluster by their contribution to divergent disease mechanisms, which allows us to define a decision boundary for a classification model. That is to say, we can use these projections of variant dynamics to train an AI classifier that predicts the impact of novel variants based on the MD results. 

An interesting result came when we applied this method to predict venetoclax resistance in BCL2. Shown below is a projection of resistant variants (red), sensitive variants (blue), and a re-sensitized double variant (rescue - first G101V, second E152A) into PCA space. The "rescue" variant becomes more wildtype, as also shown with the predicted Ki.

![image](https://user-images.githubusercontent.com/29253108/180990930-2fc7b17b-6878-4c4c-bcb7-ba063afd05fe.png)
https://www.sciencedirect.com/science/article/pii/S0010482521008544?via%3Dihub

The Ki's were predicted by quantifying the distance of a given variant from the wildtype, and our preliminary data suggests the degree of divergence from the wildtype dynamics correlates to the degree of functional change in other proteins as well (see the Biophysical Journal article linked above).

So... to what degree can these methods be used as evidence? Or on the other hand, to what degree can curated evidence be used to label/train these sorts of models?

**Comment by arpaddanos** [comment]
<img width="1156" alt="slide4" src="https://user-images.githubusercontent.com/13948978/181872346-e5830687-b6e4-4c8e-b4f5-93fc1f50c3db.png">

**Comment by mccoymd** [comment]
When it comes to labeling the lower dimensional projections of variant proteins, the evidence codes be used to establish the decision boundaries between classification models. 

Predictive -

**Comment by malachig** [comment]
Matthew provided a summary of this discussion.

**Comment by malachig** [comment]
Resolving in preparation for the 2023 hackathon/jamboree.
