### ISSUE TITLE
Curating the non-coding genome

### ISSUE THREAD

**Issue by mccoymd** [griffithlab/civic-meeting#52]
A recent publication made recommendations for the curation of non-coding variants.
https://genomemedicine.biomedcentral.com/articles/10.1186/s13073-022-01073-3

How do the germ-line recommendations apply to curation of somatic variants?

![13073_2022_1073_Fig1_HTML](https://user-images.githubusercontent.com/29253108/180993036-9076dd74-5d38-4a2d-a333-d271262d8a0d.jpeg)

**Comment by mccoymd** [comment]
Some overlap with the structural variant representation... it would be good to understand what was lost/gained in a deletion/duplication event, and its clinical significance.

**Comment by malachig** [comment]
Resolving in preparation for the 2023 hackathon/jamboree.
