### ISSUE TITLE
Gene fusion curation (Room 308)

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/civic-meeting#53]
The VICC gene fusions project, in partnership with representatives from ClinGen Somatic, CGC, and the CAP/ACMG Cytogenomics Committee, has developed a draft specification for the representation of gene fusions: [fusions.cancervariants.org](https://fusions.cancervariants.org).

I propose that a survey of existing categorical fusion concepts in the CIViC knowledgebase is evaluated under this framework and structured information collected to improve computable interpretation and search of CIViC fusion variants.

Depending on the expertise of participants, available curation tools to enable this exercise include [hypothes.is](https://web.hypothes.is/) or Jupyter notebooks leveraging [the FUSOR package](https://github.com/cancervariants/fusor).

**Comment by ahwagner** [comment]
Useful tooling: take chimeric fusion sequences and generate an assayed fusion under the specification guidelines

Example fusion sequence from this page:
https://ccsm.uth.edu/FusionGDB/gene_search_result.cgi?page=page&type=quick_search&quick_search=32394

From this, find representative transcript fusion, annotated with reading frame prediction, preserved domains, etc. and match to curated evidence

**Comment by ahwagner** [comment]
Our example exercise is capturing the ALK Fusion page from CIViC: https://civicdb.org/variants/499/summary

Our sheet for curating these variants:
https://docs.google.com/spreadsheets/d/1WCgrDAqMKj0AOk45uGEJ2koS3T4SZ_nnryHKqGB9pcg/edit?usp=sharing

**Comment by ahwagner** [comment]
A future extension for this work: how do we describe a group of genes with known oncogenic properties, for more precise representation of concepts such as Reg@IGH::v?

**Comment by ahwagner** [comment]
@bpitel12 to run a fusion protein visualization tutorial–stay tuned!

**Comment by ahwagner** [comment]
Group discussion point: workflow should get more concretely to the point of the chimeric protein being of relevance.

Generalize the critical domains to also consider regulatory (non-translated) domains within genes

IGH::MYC needs to be added to CIViC! @jsaliba10 reminded us that anyone in the community can do this. 😄

**Comment by ahwagner** [comment]
During the curation exercise, it was found that the EWSR1::FLI1 structure was defined by CIViC as:
>In approximately 90% of Ewing sarcoma/primitive neuroectodermal tumor (ES/PNET) a translocation t(11;22)(q24; q12) is identified, fusing the 5’ exons (containing the transactivation domain, at least exon 1-7) of EWSR1, with the 3’ exons (from exon 9, coding the DNA binding domain) of FLI1.

These exon structures are correct, but there is no annotated transactivation domain for EWSR1; as described in https://acsjournals.onlinelibrary.wiley.com/doi/full/10.1002/cncy.22239:

>The N-terminus (exons 1-7) mediates transcriptional activation through degenerate repeats of the SYGQ motif, whereas the C-terminus contains an 87-amino-acid RNA-recognition motif encoded by exons 11 through 13.[4](https://acsjournals.onlinelibrary.wiley.com/doi/full/10.1002/cncy.22239#cncy22239-bib-0004) Although variable, the majority (80%) of the breakpoints in EWSR1 occur in intron 7 or 8, resulting in fusion of the EWSR1 N-terminus to heterologous DNA-binding domains of its partners.

This helped us identify the need to define categorical fusions by _minimal included exons_ in addition to annotation of critical protein domains.

**Comment by ahwagner** [comment]
Add information about observed fusion junctions to the "valid fusion range" concept discussed above.

**Comment by malachig** [comment]
Summary of activities presented on behalf of the group by Beth Pitel and Alex Wagner

**Comment by bpitel12** [comment]
[Fusion Curation_CIViC 2022.pptx](https://github.com/griffithlab/civic-meeting/files/9227590/Fusion.Curation_CIViC.2022.pptx)

**Comment by skr1** [comment]
would love to be the part of working group for protein domain annotation of novel fusion and perhaps protein structure prediction as well to contribute towards their functional evidence.

**Comment by skr1** [comment]
Please indicate the name of NIH consortium working on such efforts.

**Comment by malachig** [comment]
Resolving in preparation for the 2023 hackathon/jamboree.
