### ISSUE TITLE
Identifying current variants that are complex molecular profiles (Room 305)

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/civic-meeting#54]
With the molecular profile feature slated to go live soon, we should identify complex molecular profiles that are currently in the database as a single variant. We need to parse out what the underlying variants are, how they will be combined in to a molecular profile construct/expression and add supporting descriptions/aliases/sources.

**Comment by malachig** [comment]
Susanna presented a summary of this activity.

**Comment by susannasiebert** [comment]
A WIP spreadsheet of this effort can be found here: https://docs.google.com/spreadsheets/d/1jDZ0IZN2-CuLxytM84s16B1nKsDV-1nfPQb5YhHeUvk/edit#gid=603729891

**Comment by malachig** [comment]
Resolving in preparation for the 2023 hackathon/jamboree.
