### ISSUE TITLE
Parameterizing a Digital Twin Model

### ISSUE THREAD

**Issue by arpaddanos** [griffithlab/civic-meeting#57]
The Digital Twin model is an approach to create a computation model of a real life process, while updating the model with outcomes from the real process. With this discussion we would have two goals, 1) to get a better understanding of the Digital Twin model and approach, and 2) to understand how a cancer Digital Twin model might be parameterized with curated clinical cancer variant data.
<img width="975" alt="DigitalTwin" src="https://user-images.githubusercontent.com/13948978/181871805-82af31da-03ce-48d1-9d1f-5cd84bd5f39e.png">

**Comment by mccoymd** [comment]
Cancer Patient Digital Twins (CPDT) rely on incomplete patient data to parameterize imperfect computational models, so an iterative approach is needed where model outcomes inform additional data collection. This leads to refined models and directs further data collection and so on.
During each round of modeling, patient derived data is used to constrain ranges on each of the model parameter values. A population of individual DTs, each corresponding to a unique combination of values sampled from those parameter ranges, is used to inform therapeutic strategies and additional data collection.



![image](https://user-images.githubusercontent.com/29253108/181916078-c5037379-9948-4a4a-882f-75c696a9af6b.png)

**Comment by arpaddanos** [comment]
liquid vs solid tumors. liquid advantage (ease of sample collection) vs solid advantage (more characterized variants)

**Comment by arpaddanos** [comment]
decision tree approach - can the clinical pathway be replaced by a decision tree

**Comment by arpaddanos** [comment]
Model better to work with early stage or late stage disease

**Comment by arpaddanos** [comment]
liquid tumors or NSCLC as best disease to work with

**Comment by arpaddanos** [comment]
![wjotebpard](https://user-images.githubusercontent.com/13948978/181996136-4d8e4ba6-0467-4098-ab8d-75f1ac930c02.jpg)

**Comment by skr1** [comment]
cellular imaging data (through cell transition from cancerous to drug-resistant) could be modeled with genetic mutation data, to predict gene profiles (or initial parameters for the model above) from imaging. These imaging features (texture, intensity, etc.) could be further modeled with features from radiology to find imaging correlates (or markers) there to be able to predict genomic profiles  using the selected markers.  ImaGene could be used to conduct such robust statistical and AI studies yielding transparent reports and supporting files for quick interpretations: https://www.imagene.pgxguide.org/index.php

**Comment by malachig** [comment]
Resolving in preparation for the 2023 hackathon/jamboree.
