### ISSUE TITLE
Submit CIViC data to WikiData for incorporation into GeneWiki in collaboration with SWAT4LS

### ISSUE THREAD

**Issue by obigriffith** [griffithlab/civic-meeting#6]
The 9th international Semantic Web Applications and Tools for Life Sciences (SWAT4LS) conference is occurring concurrently with the CIViC Hackathon Dec 5-8, also at the NKI in Amsterdam. In an effort to cross-pollinate between our two meetings/hackathons efforts will be made to provide CIViC data for SWAT4LS hacking. Specifically we will attempt to incorporate CIViC evidence statements into WikiData to allow semantic web applications.

**Comment by andrawaag** [comment]
As preparation for this Hackathon a datamodel [1] to capture CIViC data in Wikidata has been implemented. An initial batch of 25 CIViC records have been captured in Wikidata. During the hackathon we would like to:
1. Review the current datamodel and discuss posisble extentions. 
2. Import CIViC data completely into Wikidata.
3. Explore CIViC data in Wikidata and experiment with querying that data with other domains captured in Wikdiata.
4. Consider other relevant resources to be included
5. Draft an update cycle between CIViC and Wikidata  

[1] https://docs.google.com/document/d/1wWvbKnI0Ky0Okz3pIk0Lfxs4c2roIeH_T9W6WJQyxik/edit

**Comment by andrawaag** [comment]
For the SWAT4LS hackathon, where other semantic web resources will be integrated with CIViC data, we need mappings between the CIViC Wikidata model and external ontologies. As an additional hackathon achievement I would like to propose to draft these mappings.

**Comment by ahwagner** [comment]
This sounds like a great idea. +1
